### ISSUE TITLE
Error al compilar y ejecutar

### ISSUE THREAD

**Issue by Chitsucrap** [enzosanchezc/haze#22]
Amigo, despues de compilar recibo este error:

[13364] Module object for pyimode2_importers is NULL!
Traceback (most recent call last):
File "PyInstaller\loader\pyimod82_importers.py", line 22, in <module> File "pathlib.py", line 14, in <module>
File "urllib\parse.py", line 40, in <module>
ModuleNotFoundError: No module named ipaddress
Traceback (most recent call last):
File "PyInstaller\loader\pyiboote1_bootstrap.py", line 17, in <module>
ModuleNotFoundError: No module named 'pyimode2_importers'
[13364] Failed to execute script pyibootel bootstrap' due to unhandled exception!

Cabe recalcar que no se nada de nada, pero me pasa con las versiones 0.11 como minimo, el ejecutable .exe que ya viene compilado funciona de maravillas, pero quiero ajustar el precio a mas de 16, y eso me afecta.
Espero que tengas un buen día, y que haya una posible solucion

**Comment by juankorn** [comment]
Buenas que tal, asi yo como vos, no tengo idea de nada de programacion. Pero encontre que el error viene de la del modulo pyinstaller. Lo que hice fue cambiar en el requirements.txt la linea de la version de ese modulo. Lo deje asi.
pyinstaller==5.12.0
Luego de eso volvi a cargar las librerias necesarias y compile de nuevo. Lo que si, quise obtener la lista de juegos y se me quedo ahi colgado. Tendria que probar un poco mas.
